### PR TITLE
Fix for Range partition

### LINKED ISSUE #168: WNRangePartition merge_left and merge_right are busted
I have a (bad) fix on the way up, that just removes the merge behavior, but this will inevitably lead to fragmentation :(.

### PR DESCRIPTION
**Pull request by AWoloszyn**
Fixes #168.

### CODE REVIEW

**Comment by devpow112** [comment]
Lol, super pedantic but why the colon at the end of the title?

File: Libraries/WNContainers/inc/WNRangePartition.h [hunk 1]
```diff
@@ -307,8 +336,49 @@ inline void range_partition<NodeAllocator, T_SIZE>::release_interval(
...
     m_used_space -= token.size();
-    token.node->m_next_free = m_free_list;
-    m_free_list = token.node;
+    auto* n = token.node->merge_left_and_free();
+    if (n) {
+      m_node_allocator.free_node(token.node);
+      if (n->m_next && n->m_next->m_next_free) {
+        // We want to merge right, but this is the slow path.
+        // We have to remove this node from the free-list.
+        auto* free = m_free_list;
```
Comment (devpow112) [inline Libraries/WNContainers/inc/WNRangePartition.h:345]: I thought we were gonna try not to use `auto` that much. I guess in this case it doesn't really matter what the type is. I just find that `auto` makes code less readable.

Comment (AWoloszyn) [reply Libraries/WNContainers/inc/WNRangePartition.h]: Fixed

**Review by devpow112 — APPROVED** [review]
